// <auto-generated />
using Fundo.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fundo.Infrastructure.Migrations
{
    [DbContext(typeof(FundoDbContext))]
    partial class FundoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fundo.Domain.Entities.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1000.00m,
                            ApplicantName = "Maria Silva",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 2500.00m,
                            ApplicantName = "João Santos",
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 5000.00m,
                            ApplicantName = "Ana Oliveira",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 750.00m,
                            ApplicantName = "Carlos Pereira",
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 3200.00m,
                            ApplicantName = "Fernanda Lima",
                            Status = "Active"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
